# Generated by Django 5.2.4 on 2025-08-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("captioning_module", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyTokenUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
            ],
        ),
    ]
