# Generated by Django 5.2.4 on 2025-08-08 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("captioning_module", "0002_dailytokenusage"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="blip_text",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="image",
            name="clip_text",
            field=models.TextField(default=""),
        ),
    ]
