# Generated by Django 5.2.4 on 2025-08-11 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captioning_module', '0003_image_blip_text_image_clip_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_path',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='user_voice_text',
            new_name='file_info',
        ),
    ]
